### ISSUE TITLE
Crash on sort 1.16.1

### ISSUE THREAD

**Issue by whatthedrunk** [yuitakaa/InvTweaksReborn#8] opened 2020-07-09 19:19 UTC
Getting this crash on ATM6 https://pastebin.com/jGw0XD73

**Comment by whatthedrunk** [comment] 2020-07-09 19:49
Here is another https://pastebin.com/Xgvt4sST

**Comment by tugboat-maguire** [comment] 2020-07-11 02:22
same here: https://pastebin.com/89AHwbPM

**Comment by reo-ar** [comment] 2020-07-11 06:30
Please do remove Optifine if it's a screen related bug, also for the third issue Paper servers aren't supported because they handle some things different.

Pushing an update with more null checks to see if it helps

**Comment by reo-ar** [comment] 2020-07-12 06:04
Closing this as it's redundant and the issue is in the megathread

**Closed as completed by reo-ar** 2020-07-12 06:04 UTC
